export {
  getOauthClientIdFromRegion,
  OAUTH_SCOPE_VERSION,
  OAUTH_SCOPES,
  POSTHOG_DEV_CLIENT_ID,
  POSTHOG_EU_CLIENT_ID,
  POSTHOG_US_CLIENT_ID,
  TOKEN_REFRESH_BUFFER_MS,
  TOKEN_REFRESH_FORCE_MS,
} from "@posthog/shared";
