/**
 * Auto-register all IPC services
 * This file is auto-generated by vite-plugin-auto-services.ts
 */

import "./dev-toolbar.js";
import "./integration-flow-schemas.js";
import "./posthog-analytics.js";
import "./settingsStore.js";
